fix spelling of postpartum
ideacrew/aca_entities pull request #21
Opened 2021-06-04 01:52 UTC by markgoho

2021-06-10 13:47 UTC, saikumar9 requested changes
Please review the comments and make the required changes.

2021-06-10 13:47 UTC, saikumar9 commented on lib/aca_entities/magi_medicaid/mitc/transformers/mitc_to/request.rb
> +                  map 'is_in_postpartum_period', 'Applicant Postpartum Period Indicator'
_MAGI In The Cloud_ expects us to send the attribute name as 'Applicant Post Partum Period Indicator'. Please revert this change.

2021-06-10 13:47 UTC, saikumar9 commented on spec/support/magi_medicaid/mitc/eligibility_request.json
> +      "Applicant Postpartum Period Indicator": "N",
_MAGI In The Cloud_ expects us to send the attribute name as 'Applicant Post Partum Period Indicator'. Please revert this change.

2021-06-10 13:47 UTC, saikumar9 commented on spec/support/magi_medicaid/mitc/eligibility_request.json
> +      "Applicant Postpartum Period Indicator": "N",
_MAGI In The Cloud_ expects us to send the attribute name as 'Applicant Post Partum Period Indicator'. Please revert this change.

2021-06-10 13:47 UTC, saikumar9 commented on spec/aca_entities/magi_medicaid/mitc/transformers/mitc_to/request_spec.rb
> +        expect(person).to have_key(:'Applicant Postpartum Period Indicator')
Revert this change as well.

2021-06-10 13:47 UTC, saikumar9 commented on spec/aca_entities/magi_medicaid/mitc/transformers/mitc_to/request_spec.rb
> +        expect(person[:'Applicant Postpartum Period Indicator']).to eq(person1[:is_in_postpartum_period])
Revert this change as well.

2021-08-26 18:49 UTC, markgoho commented
@saikumar9 the spelling is incorrect, the answer is not to revert the change, it's to fix it upstream: pull request here: https://github.com/ideacrew/medicaid_eligibility/pull/4

2021-09-17 14:26 UTC, closed without merging